language: node_js
node_js:
  - 0.10
install:
  - npm install
  - npm install -g grunt-cli
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
email:
  - ci@dica-developer.org